language: python
python:
    - "3.4"
    - "3.6"
install:
    - sudo apt install -y gcc g++
    - pip install flake8 cpplint
script:
    - flake8
    - cpplint --quiet --recursive --filter="-legal/copyright,-runtime/int,-runtime/arrays" .
    - ./run_all.sh
notifications:
    email:
        - arcursino@gmail.com
